#!/usr/bin/env python3
"""Build-time RETRIEVAL PROJECTION for RAG / agent developers (ticket #523).

The published ontology spreads a single citeable provision across three nodes in
two files: the provision node (``estleg:legalText`` + ``estleg:paragrahv``), its
``estleg:ProvisionVersion`` nodes (``versionText`` + ``versionRedactionId`` +
``versionValidFrom``), and the act root (``dcterms:title`` + Riigi Teataja URL +
``estleg:kehtiv``). A retrieval consumer therefore has to reassemble 3 nodes
across 2 files to cite one paragraph, and a provision node's bytes are dominated
by unbounded ``interpretedBy`` / ``referencedBy`` IRI arrays. This generator
flattens the graph into four self-contained, citeable projections:

1. ``chunks.jsonl`` -- one flat record PER PROVISION-VERSION (the core retrieval
   unit). For a §-level provision that has a version layer, one record per
   version; for a provision with no version layer, one record from the
   consolidated text. Each record is independently citeable
   (``provision_iri`` + ``rt_url`` + ``paragraph``) and carries the untruncated
   text plus the validity window and an ``in_force`` flag. Since #723 every
   record also carries an **audit envelope** (``chunk_id``,
   ``ontology_version``, ``evaluation_date``, ``act_iri``, ``kehtiv``,
   ``language``, ``part_index``/``part_count``) so a chunk copied into a RAG
   store can be traced months later from the record alone; see
   :data:`CHUNK_KEYS` and :data:`CHUNK_SCHEMA_VERSION`. With ``--max-chars`` a
   long § is split on sentence boundaries into parts (``#part_<k>`` suffix on
   ``chunk_id``).
2. ``outlines/<law>.json`` -- a per-law skim tier: ``{paragraph, label, chapter,
   summary (<=120 chars), has_versions}`` per provision, so a consumer can
   navigate a multi-megabyte law without fetching the whole thing.
3. ``context_packs/<law>.json`` -- a per-law DENORMALISED bundle: provisions +
   versions + references + cases + amendments + sanctions in ONE fetch.
4. ``llms.txt`` -- a served plain-text entry point (https://llmstxt.org) that
   describes the corpus and points at the projections.

Design notes
------------
* The provision-version unit is **§-level**: ``estleg:LegalProvision_*`` nodes
  (those carry ``estleg:paragrahv`` and ``estleg:hasVersion``). ``estleg:
  Subsection`` (lõige) nodes are NOT separate retrieval units -- their text is
  already contained in the parent §'s ``estleg:legalText``.
* The version layer keys by ``estleg:versionOf`` (the §). ``in_force`` is
  computed from the validity window against the pinned evaluation date, so it is
  deterministic and date-stable (issue #262/#295 pattern).
* Riigi Teataja URLs and act titles are read off the act root via the same
  fields the canonical builders write (``dcterms:source`` / ``dcterms:title`` /
  ``dc:source`` / ``rdfs:label``); abbreviations come from
  ``data/law_abbreviations.json`` (the registry the URI migration maintains).
* **Determinism** (AGENTS.md): laws are processed in sorted order, provisions by
  IRI, versions by ``(validFrom, redactionId, @id)``; no wall-clock timestamps
  (the pinned ``ESTLEG_BUILD_EVALUATION_DATE`` / ``ONTOLOGY_VERSION`` are the
  only stamps); no ``set()`` iteration without a surrounding ``sorted()``. Two
  consecutive runs over the same corpus are byte-identical.

The artifacts live under ``krr_outputs/retrieval/``, which
``estleg_common.is_operational_state_file`` excludes from the corpus file
counter (the same status as ``reports/integration/`` pipeline manifests) so the
projection never drifts the pinned ``metadata.jsonld`` ``estleg:totalFiles``
count nor reaches ``validate_all`` / SHACL.

DAG placement (#705): the combined rebuild (``build_release_artifacts.py``)
is the last ENRICHMENT-side step; ``package``-tier steps that only read the
built corpus may follow it. ``build_release_assets.py`` (the last DAG step)
calls :func:`generate` with ``chunks_only=True`` into
``release/retrieval/`` and ships ``chunks.jsonl.gz``; the
committed projection here (README / llms.txt / samples / manifest) is still
regenerated by running this script directly.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

from estleg.estleg_common import (
    BUILD_EVALUATION_DATE,
    KRR_DIR,
    NS,  # noqa: F401 — re-exported; tests import generate_retrieval_projection.NS
    ONTOLOGY_VERSION,
    REPO_ROOT,
    act_deprecation,
    act_prefix_from_iri,
    act_root_node,
    jsonld_text,
    save_json,
)
from estleg.write_build_manifest import github_release_asset_url

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------
DATA_DIR = REPO_ROOT / "data"
ABBREV_REGISTRY_PATH = DATA_DIR / "law_abbreviations.json"
DEFAULT_OUT_DIRNAME = "retrieval"
PROVISION_VERSIONS_DIRNAME = "provision_versions"
AMENDMENTS_DIRNAME = "amendments"
SANCTIONS_DIRNAME = "sanctions"
COURT_DIRNAMES = ("riigikohus", "curia")

SUMMARY_MAX = 120
SAMPLE_CHUNKS_DEFAULT = 200
SAMPLE_LAW_DEFAULT = "alkoholiseadus"

# riigiteataja.ee browse URL for an act; the corpus stores the resolvable
# source IRI with a trailing ``.xml`` (XML endpoint) -- strip it for the
# human/agent-facing citation, which renders HTML.
_RT_XML_SUFFIX = ".xml"

# Provision node @type prefix; subsection (lõige) nodes are estleg:Subsection
# and are deliberately NOT treated as provision-version units.
_PROVISION_TYPE_PREFIX = "estleg:LegalProvision"

# ---------------------------------------------------------------------------
# Chunk record contract (#723)
# ---------------------------------------------------------------------------
# Version of the chunk RECORD schema (independent of ONTOLOGY_VERSION). Bump
# the major on a key removal/rename or a semantic change, the minor on an
# additive key. 1.0.0 was the ten-key #523 record; 2.0.0 adds the audit
# envelope, part fields, and the provision-level ``rt_url``.
CHUNK_SCHEMA_VERSION = "2.0.0"

# Every record carries exactly these keys, always in this order (byte-stable
# JSONL). Nullable: redaction_id, abbrev, rt_url, valid_from, valid_to, kehtiv,
# act_iri.
CHUNK_KEYS: tuple[str, ...] = (
    "chunk_id",
    "provision_iri",
    "act_iri",
    "redaction_id",
    "paragraph",
    "act_title",
    "abbrev",
    "rt_url",
    "valid_from",
    "valid_to",
    "in_force",
    "kehtiv",
    "evaluation_date",
    "ontology_version",
    "language",
    "part_index",
    "part_count",
    "text",
)

# (type, meaning/source) per key -- rendered into the generated README and
# kept here so the documented contract cannot drift from CHUNK_KEYS.
CHUNK_FIELD_DOCS: dict[str, tuple[str, str]] = {
    "chunk_id": ("string", "Stable id: `<provision_iri>#<redaction_id>` or `<provision_iri>#consolidated`, plus `#part_<k>` when split."),
    "provision_iri": ("string (CURIE)", "§-level `estleg:LegalProvision_*` node."),
    "act_iri": ("string (CURIE) or null", "Act root node of the peep file the § was read from."),
    "redaction_id": ("string or null", "`estleg:versionRedactionId` (RT redaction); null for consolidated text."),
    "paragraph": ("string", "`estleg:paragrahv` label, e.g. `§ 13¹.`."),
    "act_title": ("string", "Act root `dcterms:title` (fallback `dc:source`, `rdfs:label`)."),
    "abbrev": ("string or null", "`data/law_abbreviations.json`, else derived from the act root id."),
    "rt_url": ("string or null", "Version sidecar `estleg:rtUrl` (redaction page), else act `dcterms:source`; `.xml` stripped; `#para<N>[b<k>]` anchor."),
    "valid_from": ("date or null", "`estleg:versionValidFrom`; act `kehtiv` for consolidated text."),
    "valid_to": ("date or null", "`estleg:versionValidTo`; null = open-ended."),
    "in_force": ("boolean", "Validity window contains `evaluation_date`; consolidated text also requires act `estleg:temporalStatus` to be in force."),
    "kehtiv": ("date or null", "Act root `estleg:kehtiv`: consolidation date of the act snapshot."),
    "evaluation_date": ("date", "Pinned `ESTLEG_BUILD_EVALUATION_DATE` that `in_force` was computed against."),
    "ontology_version": ("string", "`ONTOLOGY_VERSION` of the build (release tag `v<version>`)."),
    "language": ("string", "BCP 47 tag of `text` / `act_title` (`et`)."),
    "part_index": ("integer", "1-based part number (1 when not split)."),
    "part_count": ("integer", "Number of parts of this provision-version (1 when not split)."),
    "text": ("string", "Untruncated `estleg:versionText` (consolidated: `estleg:legalText`), or one part of it."),
}

# Language of ``text`` / ``act_title`` (BCP 47). The projection only reads
# the Estonian-language state-law corpus (INDEX laws).
CHUNK_LANGUAGE = "et"

# chunk_id segment for a provision with no version layer (consolidated text).
CONSOLIDATED_SEGMENT = "consolidated"

# Release asset the #705 release step gzips from this generator's output.
CHUNKS_ASSET_NAME = "chunks.jsonl.gz"

# Smallest accepted --max-chars (guards against degenerate one-word parts).
MIN_MAX_CHARS = 200

# Riigi Teataja renders each § with an element id ``para<N>`` and a
# superscripted § (``§ 13¹``) as ``para<N>b<k>`` -- the ids are present in the
# act XML (``<paragrahv id="para13b1">``) and the www.riigiteataja.ee SPA
# resolves them with ``getElementById`` (router ``anchorScrolling: enabled``).
_PARAGRAPH_NUMBER_RE = re.compile(
    r"§\s*(\d+)\s*(?:([⁰¹²³⁴⁵⁶⁷⁸⁹]+)|\^\s*(\d+))?"
)
_SUPERSCRIPT_DIGITS = str.maketrans("⁰¹²³⁴⁵⁶⁷⁸⁹", "0123456789")


# ---------------------------------------------------------------------------
# Small JSON-LD accessors (kept local + pure for unit testing)
# ---------------------------------------------------------------------------
def _load_json(path: Path, *, required: bool = False) -> Any | None:
    """Load JSON from ``path``; return ``None`` on a missing/corrupt file."""
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError) as exc:
        if required:
            raise ValueError(f"Cannot read retrieval input {path}: {exc}") from exc
        return None


def _load_graph_json(path: Path) -> Any:
    doc = _load_json(path, required=True)
    graph = doc.get("@graph") if isinstance(doc, dict) else doc
    if not isinstance(graph, list) or not all(isinstance(node, dict) for node in graph):
        raise ValueError(f"Invalid retrieval graph input: {path}")
    return doc


def _graph(doc: Any) -> list[dict]:
    """Return the ``@graph`` list of a JSON-LD document (or ``[]``)."""
    if isinstance(doc, dict):
        graph = doc.get("@graph")
        if isinstance(graph, list):
            return [n for n in graph if isinstance(n, dict)]
        return []
    if isinstance(doc, list):
        return [n for n in doc if isinstance(n, dict)]
    return []


def _types(node: dict) -> list[str]:
    """Return ``@type`` as a list of strings."""
    raw = node.get("@type") or []
    if isinstance(raw, str):
        return [raw]
    return [t for t in raw if isinstance(t, str)]


def _ref_ids(value: Any) -> list[str]:
    """Return every ``@id`` reachable in a JSON-LD object/list/string value."""
    out: list[str] = []
    if isinstance(value, str):
        out.append(value)
    elif isinstance(value, dict):
        ref = value.get("@id")
        if isinstance(ref, str):
            out.append(ref)
    elif isinstance(value, list):
        for item in value:
            out.extend(_ref_ids(item))
    return out


def _ref_id(value: Any) -> str | None:
    """Return the first ``@id`` in a JSON-LD value, else ``None``."""
    ids = _ref_ids(value)
    return ids[0] if ids else None


def _strip_xml(url: str | None) -> str | None:
    """Return the browseable RT URL: drop a trailing ``.xml`` endpoint suffix."""
    if not url:
        return None
    if url.endswith(_RT_XML_SUFFIX):
        return url[: -len(_RT_XML_SUFFIX)]
    return url


def _rt_browse_url(url: str | None) -> str | None:
    if not url:
        return None
    try:
        parts = urlsplit(url)
        host = (parts.hostname or "").lower()
        if parts.scheme not in {"http", "https"} or not (
            host == "riigiteataja.ee" or host.endswith(".riigiteataja.ee")
        ):
            return None
    except ValueError:
        return None
    return urlunsplit(parts._replace(path=parts.path.removesuffix(".xml"), fragment=""))


# ---------------------------------------------------------------------------
# Act-root resolution (title / rt_url / kehtiv / abbreviation / status)
# ---------------------------------------------------------------------------
def find_act_root(graph: list[dict]) -> dict | None:
    """Return the act-root individual, else a bare ontology header."""
    return act_root_node({"@graph": graph})


def act_title(root: dict | None) -> str:
    """Resolve the act title: dcterms:title -> dc:source -> rdfs:label.

    A bilingual title list (``et`` + ``en``) resolves to the Estonian value so
    ``act_title`` agrees with the record's ``language`` (#723); an untagged or
    English-only title still falls back to whatever text is present.
    """
    if not root:
        return ""
    for key in ("dcterms:title", "dc:source", "rdfs:label"):
        text = jsonld_text(root.get(key), prefer_language=CHUNK_LANGUAGE)
        if text:
            return text
    return ""


def act_rt_url(root: dict | None) -> str | None:
    """Resolve the act's Riigi Teataja browse URL from the act root.

    Reads ``dcterms:source`` (the canonical resolvable IRI the builders write),
    falling back to ``owl:sameAs``; the stored value is the ``.xml`` endpoint,
    which is normalised to the HTML browse URL.
    """
    if not root:
        return None
    for key in ("dcterms:source", "owl:sameAs"):
        for ref in _ref_ids(root.get(key)):
            url = _rt_browse_url(ref)
            if url:
                return url
    # Legacy dc:source may itself be a URL.
    legacy = jsonld_text(root.get("dc:source"))
    return _rt_browse_url(legacy)


def act_kehtiv(root: dict | None) -> str | None:
    """Return the act consolidation date (``estleg:kehtiv``) or ``None``."""
    if not root:
        return None
    return jsonld_text(root.get("estleg:kehtiv")) or None


def act_in_force(root: dict | None) -> bool:
    """Return True when the act root's ``estleg:temporalStatus`` is in force.

    Used only for provisions with no version layer (the consolidated peep IS
    the current text). Unknown status is treated as in force, matching the
    consolidated-text assumption.
    """
    if not root:
        return True
    status = jsonld_text(root.get("estleg:temporalStatus"))
    if not status:
        return True
    return status == "inForce"


def derive_abbrev(act_id: str | None) -> str | None:
    """Derive a law abbreviation from an act-root ``@id`` (registry fallback).

    ``estleg:AS_Map_2026`` -> ``AS``; ``estleg:AÕS_Osa1_...`` -> ``AÕS``;
    also handles ``_ProcedureMap`` / ``_Ontology`` / ``_TopicScheme`` roots.
    """
    if not act_id:
        return None
    return act_prefix_from_iri(act_id)


def resolve_abbrev(
    registry: dict[str, dict],
    file_slug: str,
    law_name: str,
    root: dict | None,
) -> str | None:
    """Resolve a law abbreviation, preferring the registry over derivation."""
    for key in (file_slug, law_name):
        entry = registry.get(key)
        if isinstance(entry, dict):
            abbrev = entry.get("abbrev")
            if abbrev:
                return abbrev
    return derive_abbrev(_ref_id(root) or (root or {}).get("@id"))


# ---------------------------------------------------------------------------
# Provision + version accessors
# ---------------------------------------------------------------------------
def is_provision(node: dict) -> bool:
    """True for a §-level provision node (excludes subsections/chapters)."""
    return any(t.startswith(_PROVISION_TYPE_PREFIX) for t in _types(node))


def provision_text(node: dict) -> str:
    """Consolidated provision text: legalText, falling back to summary."""
    return jsonld_text(node.get("estleg:legalText")) or jsonld_text(
        node.get("estleg:summary")
    )


def truncate_summary(text: str, max_len: int = SUMMARY_MAX) -> str:
    """Return ``text`` collapsed to a single line of at most ``max_len`` chars.

    Whitespace is collapsed; an over-length string is cut and suffixed with an
    ellipsis so the result never exceeds ``max_len`` characters.
    """
    collapsed = " ".join(text.split())
    if len(collapsed) <= max_len:
        return collapsed
    if max_len <= 3:
        return collapsed[:max_len]
    return collapsed[: max_len - 3].rstrip() + "..."


def chapter_label(node: dict, id_label: dict[str, str]) -> str | None:
    """Resolve a provision's chapter label via ``estleg:isPartOf``."""
    parent = _ref_id(node.get("estleg:isPartOf"))
    if not parent:
        return None
    return id_label.get(parent)


def _version_record(node: dict) -> tuple[str, dict] | None:
    """Return ``(provision_iri, version-field dict)`` for a ProvisionVersion."""
    if "estleg:ProvisionVersion" not in _types(node):
        return None
    provision_iri = _ref_id(node.get("estleg:versionOf"))
    if not provision_iri:
        return None
    return provision_iri, {
        "iri": node.get("@id"),
        "redaction_id": jsonld_text(node.get("estleg:versionRedactionId")) or None,
        "valid_from": jsonld_text(node.get("estleg:versionValidFrom")) or None,
        "valid_to": jsonld_text(node.get("estleg:versionValidTo")) or None,
        "text": jsonld_text(node.get("estleg:versionText")),
        # Per-redaction RT URL (``estleg:rtUrl``) -- a plain string or {"@id"}.
        "rt_url": _strip_xml(
            _ref_id(node.get("estleg:rtUrl"))
            or jsonld_text(node.get("estleg:rtUrl"))
            or None
        ),
    }


def load_version_map(versions_dir: Path) -> dict[str, list[dict]]:
    """Return a GLOBAL ``{provision_iri: [version dicts]}`` map.

    Keyed by ``estleg:versionOf`` over EVERY version file, so a provision
    resolves to its versions regardless of which file holds either node. This
    matters for multi-part codes (``asjaoigusseadus``, ``karistusseadustik``,
    …) whose version layer is a single law-named file while the peeps are split
    by ``osa`` — a per-file pairing would strand ~7% of versions. Each version
    dict is ``{iri, redaction_id, valid_from, valid_to, text}`` and the
    per-provision list is ordered by ``(valid_from, redaction_id, iri)`` so
    chunk emission is byte-stable.
    """
    out: dict[str, list[dict]] = {}
    if not versions_dir.is_dir():
        return out
    for path in sorted(versions_dir.glob("*.jsonld")):
        doc = _load_graph_json(path)
        for node in _graph(doc):
            record = _version_record(node)
            if record is None:
                continue
            provision_iri, fields = record
            out.setdefault(provision_iri, []).append(fields)
    for versions in out.values():
        versions.sort(
            key=lambda v: (
                v["valid_from"] or "",
                v["redaction_id"] or "",
                v["iri"] or "",
            )
        )
    return out


def compute_in_force(
    valid_from: str | None, valid_to: str | None, eval_date: str
) -> bool:
    """True when ``[valid_from, valid_to]`` contains ``eval_date``.

    ISO ``YYYY-MM-DD`` dates compare lexically. A missing ``valid_from`` means
    "already started"; a missing ``valid_to`` means "open-ended / current".
    """
    if valid_from and valid_from > eval_date:
        return False
    if valid_to and valid_to < eval_date:
        return False
    return True


# ---------------------------------------------------------------------------
# Chunk envelope helpers (#723)
# ---------------------------------------------------------------------------
def paragraph_anchor(paragraph: str | None) -> str | None:
    """Return the Riigi Teataja HTML anchor for a § label, else ``None``.

    ``"§ 5."`` -> ``"para5"``; ``"§ 13¹."`` / ``"§ 13^1"`` -> ``"para13b1"``.
    The number is read from the source ``estleg:paragrahv`` label (not the
    IRI, which can lag a renumbering).
    """
    if not paragraph:
        return None
    match = _PARAGRAPH_NUMBER_RE.search(paragraph)
    if not match:
        return None
    number, sup, caret = match.groups()
    anchor = f"para{number}"
    sub = sup.translate(_SUPERSCRIPT_DIGITS) if sup else caret
    if sub:
        anchor += f"b{sub}"
    return anchor


def provision_rt_url(
    redaction_url: str | None, act_url: str | None, paragraph: str | None
) -> str | None:
    """Return the provision-level RT URL for one chunk.

    Base: the redaction's own ``estleg:rtUrl`` (the text exactly as cited)
    when it is an http(s) URL, else the act browse URL. A ``#para<N>[b<k>]``
    fragment is appended when the § number parses; otherwise the bare base.
    """
    base = _rt_browse_url(redaction_url) or _rt_browse_url(act_url)
    if not base:
        return None
    base = base.split("#", 1)[0]
    anchor = paragraph_anchor(paragraph)
    return f"{base}#{anchor}" if anchor else base


def make_chunk_id(
    provision_iri: str,
    redaction_id: str | None,
    part_index: int = 1,
    part_count: int = 1,
) -> str:
    """Return the stable chunk identifier.

    ``<provision_iri>#<redaction_id>`` for a version record,
    ``<provision_iri>#consolidated`` for a provision with no version layer, and
    a ``#part_<k>`` suffix (1-based) only when the text was split. The id is a
    pure function of the provision, the RT redaction, and the split position,
    so it is stable across rebuilds of the same corpus with the same
    ``--max-chars``.
    """
    chunk_id = f"{provision_iri}#{redaction_id or CONSOLIDATED_SEGMENT}"
    if part_count > 1:
        chunk_id += f"#part_{part_index}"
    return chunk_id


# Sentence-final punctuation followed by whitespace, or whitespace before a
# lõige marker ``(2)`` / ``(2¹)``: the candidate cut points for splitting.
_CUT_RE = re.compile(r"(?<=[.!?;:])\s+|\s+(?=\(\d+[⁰¹²³⁴⁵⁶⁷⁸⁹]*\)\s)")
# Token before a full stop that does NOT end a sentence: an ordinal / §
# number ("§ 5.", "1. jaanuar") or a common Estonian legal abbreviation.
_NON_TERMINAL_TOKEN_RE = re.compile(
    r"^[(\[«\"']*(?:\d+[⁰¹²³⁴⁵⁶⁷⁸⁹]*|nr|lg|p|jne|jm|vms|nt|st|s\.t|k\.a|"
    r"v\.a|art|lk|tk|kd|mh|sh|pt|ptk|ca|u|vt|vrd|nn|eKr|pKr|hr|pr|dr)\.$",
    re.IGNORECASE,
)


def _cut_points(text: str) -> list[int]:
    """Return sorted cut offsets (each the START of the next segment)."""
    cuts: set[int] = set()
    for match in _CUT_RE.finditer(text):
        before = text[: match.start()]
        tail = before.rsplit(None, 1)
        token = tail[-1] if tail else ""
        if token.endswith(".") and _NON_TERMINAL_TOKEN_RE.search(token):
            continue
        if match.end() < len(text):
            cuts.add(match.end())
    return sorted(cuts)


def _hard_split(segment: str, max_chars: int) -> list[str]:
    """Split one over-long segment at whitespace (else mid-word) <= max_chars."""
    out: list[str] = []
    rest = segment
    while len(rest.strip()) > max_chars:
        window = rest[: max_chars + 1]
        cut = window.rstrip().rfind(" ")
        if cut <= 0:
            cut = max_chars
        out.append(rest[:cut])
        rest = rest[cut:]
    if rest.strip():
        out.append(rest)
    return out


def split_text(text: str, max_chars: int | None) -> list[str]:
    """Split ``text`` into parts of at most ``max_chars`` characters.

    ``None`` (the default) or a text that already fits returns ``[text]``
    unchanged. Otherwise the text is cut at sentence boundaries (sentence-final
    ``. ! ? ; :`` -- not after an ordinal or a legal abbreviation -- and before a
    lõige marker ``(N)``) and consecutive sentences are packed greedily; a single
    sentence longer than ``max_chars`` is cut at the last space. Parts are
    contiguous slices of ``text`` with the whitespace at each cut dropped, so
    ``" ".join(parts)`` equals ``text`` up to whitespace at the cut points.
    """
    if max_chars is None or len(text) <= max_chars:
        return [text]
    bounds = [0, *_cut_points(text), len(text)]
    segments: list[str] = []
    for start, end in zip(bounds, bounds[1:], strict=False):
        segment = text[start:end]
        if len(segment.strip()) > max_chars:
            segments.extend(_hard_split(segment, max_chars))
        else:
            segments.append(segment)
    parts: list[str] = []
    current = ""
    for segment in segments:
        candidate = current + segment
        if current and len(candidate.strip()) > max_chars:
            parts.append(current.strip())
            current = segment
        else:
            current = candidate
    if current.strip():
        parts.append(current.strip())
    return parts or [text]


def generator_commit() -> str | None:
    """Return the git commit the generator runs from (``None`` if unknown).

    ``ESTLEG_GENERATOR_COMMIT`` overrides (CI / release builds from a tarball).
    Recorded in ``manifest.json`` only -- never in the chunk records -- so the
    record bytes stay a pure function of the corpus.
    """
    override = os.environ.get("ESTLEG_GENERATOR_COMMIT")
    if override:
        return override.strip() or None
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    sha = out.stdout.strip()
    return sha or None


def chunks_asset_url(version: str = ONTOLOGY_VERSION) -> str:
    """Return the tagged GitHub release download URL of ``chunks.jsonl.gz``."""
    return github_release_asset_url(CHUNKS_ASSET_NAME, version)


# ---------------------------------------------------------------------------
# Chunk assembly (the core retrieval unit)
# ---------------------------------------------------------------------------
def build_chunk_record(
    *,
    provision_iri: str,
    redaction_id: str | None,
    paragraph: str,
    act_title_str: str,
    abbrev: str | None,
    rt_url: str | None,
    valid_from: str | None,
    valid_to: str | None,
    in_force: bool,
    text: str,
    act_iri: str | None = None,
    kehtiv: str | None = None,
    evaluation_date: str,
    ontology_version: str = ONTOLOGY_VERSION,
    language: str = CHUNK_LANGUAGE,
    part_index: int = 1,
    part_count: int = 1,
) -> dict:
    """Assemble one flat, self-contained provision-version record.

    Keys are emitted in :data:`CHUNK_KEYS` order so JSONL serialisation is
    byte-stable across runs. ``chunk_id`` is derived (:func:`make_chunk_id`).
    """
    record = {
        "chunk_id": make_chunk_id(provision_iri, redaction_id, part_index, part_count),
        "provision_iri": provision_iri,
        "act_iri": act_iri,
        "redaction_id": redaction_id,
        "paragraph": paragraph,
        "act_title": act_title_str,
        "abbrev": abbrev,
        "rt_url": rt_url,
        "valid_from": valid_from,
        "valid_to": valid_to,
        "in_force": in_force,
        "kehtiv": kehtiv,
        "evaluation_date": evaluation_date,
        "ontology_version": ontology_version,
        "language": language,
        "part_index": part_index,
        "part_count": part_count,
        "text": text,
    }
    return record


def build_chunk_records(*, text: str, max_chars: int | None, **fields: Any) -> list[dict]:
    """Return the record(s) for one provision-version, split per ``max_chars``."""
    parts = split_text(text, max_chars)
    count = len(parts)
    return [
        build_chunk_record(text=part, part_index=index, part_count=count, **fields)
        for index, part in enumerate(parts, start=1)
    ]


# ---------------------------------------------------------------------------
# Court-decision index (for context-pack case resolution)
# ---------------------------------------------------------------------------
def build_decision_index(krr_dir: Path) -> dict[str, dict]:
    """Map ``CourtDecision`` @id -> ``{case_number, decision_link, decision_date}``.

    Streams each court peep file (extracting only three fields) so the index
    stays small even though the underlying corpus is large.
    """
    index: dict[str, dict] = {}
    for dirname in COURT_DIRNAMES:
        court_dir = krr_dir / dirname
        if not court_dir.is_dir():
            continue
        for path in sorted(court_dir.glob("*_peep.json")):
            doc = _load_json(path)
            if doc is None:
                continue
            for node in _graph(doc):
                if "estleg:CourtDecision" not in _types(node):
                    continue
                node_id = node.get("@id")
                if not isinstance(node_id, str) or node_id in index:
                    continue
                index[node_id] = {
                    "iri": node_id,
                    "case_number": jsonld_text(node.get("estleg:caseNumber"))
                    or None,
                    "decision_link": jsonld_text(node.get("estleg:decisionLink"))
                    or None,
                    "decision_date": jsonld_text(node.get("estleg:decisionDate"))
                    or None,
                }
    return index


# ---------------------------------------------------------------------------
# Overlay loaders (amendments / sanctions for a law)
# ---------------------------------------------------------------------------
def _overlay_nodes(krr_dir: Path, subdir: str, prefix: str, *slugs: str) -> list[dict]:
    """Return the UNION of individual (non-Ontology) overlay nodes for a law.

    For a multi-part code the overlay files are keyed by peep FILE STEM
    (``sanctions_karistusseadustik_osa1`` + ``…_osa2``), not by the law name,
    so a single ``law_name`` lookup misses them entirely. Every candidate slug
    is therefore tried and the resolving files' nodes are UNIONed —
    deduplicated by ``@id``, preserving slug-then-file order — rather than
    returning only the first that resolves (which would also strand all but the
    first ``osa``). The ``owl:Ontology`` wrapper of each file is dropped.
    """
    overlay_dir = krr_dir / subdir
    out: list[dict] = []
    seen_slugs: set[str] = set()
    seen_ids: set[str] = set()
    for slug in slugs:
        if not slug or slug in seen_slugs:
            continue
        seen_slugs.add(slug)
        doc = _load_json(overlay_dir / f"{prefix}{slug}.json")
        if doc is None:
            continue
        for node in _graph(doc):
            if "owl:Ontology" in _types(node):
                continue
            node_id = node.get("@id")
            if isinstance(node_id, str):
                if node_id in seen_ids:
                    continue
                seen_ids.add(node_id)
            out.append(node)
    return out


# ---------------------------------------------------------------------------
# Per-law processing
# ---------------------------------------------------------------------------
class _LawAccumulator:
    """Mutable per-law accumulator across a law's (possibly multi-part) files."""

    def __init__(self, law_name: str) -> None:
        self.law_name = law_name
        self.title = ""
        self.abbrev: str | None = None
        self.rt_url: str | None = None
        self.kehtiv: str | None = None
        self.in_force = True
        self.header_set = False
        self.chunks: list[dict] = []
        self.outline: list[dict] = []
        self.provisions: list[dict] = []
        self.versions: list[dict] = []
        self.case_ids: set[str] = set()
        # Peep file stems of this (possibly multi-part) law, in sorted-file
        # order; overlay files for osa-split codes are keyed by these stems.
        self.file_slugs: list[str] = []


def process_law_file(
    doc: Any,
    *,
    file_slug: str,
    law_name: str,
    registry: dict[str, dict],
    version_map: dict[str, list[dict]],
    eval_date: str,
    acc: _LawAccumulator,
    max_chars: int | None = None,
) -> None:
    """Fold one peep file's provisions into the per-law accumulator."""
    if file_slug not in acc.file_slugs:
        acc.file_slugs.append(file_slug)
    graph = _graph(doc)
    root = find_act_root(graph)
    title = act_title(root)
    abbrev = resolve_abbrev(registry, file_slug, law_name, root)
    rt_url = act_rt_url(root)
    kehtiv = act_kehtiv(root)
    act_active = act_in_force(root)
    act_iri = root.get("@id") if isinstance((root or {}).get("@id"), str) else None
    # Envelope fields shared by every chunk of this file (#723).
    envelope = {
        "act_iri": act_iri,
        "act_title_str": title,
        "abbrev": abbrev,
        "kehtiv": kehtiv,
        "evaluation_date": eval_date,
    }

    if not acc.header_set:
        acc.title = title
        acc.abbrev = abbrev
        acc.rt_url = rt_url
        acc.kehtiv = kehtiv
        acc.in_force = act_active
        acc.header_set = True

    id_label = {
        n["@id"]: jsonld_text(n.get("rdfs:label"))
        for n in graph
        if isinstance(n.get("@id"), str) and n.get("rdfs:label")
    }

    provisions = sorted(
        (n for n in graph if is_provision(n)),
        key=lambda n: n.get("@id") or "",
    )
    for node in provisions:
        provision_iri = node.get("@id")
        if not isinstance(provision_iri, str):
            continue
        paragraph = jsonld_text(node.get("estleg:paragrahv"))
        label = jsonld_text(node.get("rdfs:label"))
        chapter = chapter_label(node, id_label)
        consolidated_text = provision_text(node)
        # pop (not get): each provision @id is globally unique, so consuming
        # the entry drains the resident version map as the run progresses.
        versions = version_map.pop(provision_iri, [])

        # --- chunks: one per version, else one consolidated record ---
        if versions:
            for ver in versions:
                in_force = compute_in_force(
                    ver["valid_from"], ver["valid_to"], eval_date
                )
                acc.chunks.extend(
                    build_chunk_records(
                        provision_iri=provision_iri,
                        redaction_id=ver["redaction_id"],
                        paragraph=paragraph,
                        rt_url=provision_rt_url(ver.get("rt_url"), rt_url, paragraph),
                        valid_from=ver["valid_from"],
                        valid_to=ver["valid_to"],
                        in_force=in_force,
                        text=ver["text"],
                        max_chars=max_chars,
                        **envelope,
                    )
                )
                acc.versions.append(
                    {
                        "iri": ver["iri"],
                        "provision_iri": provision_iri,
                        "redaction_id": ver["redaction_id"],
                        "valid_from": ver["valid_from"],
                        "valid_to": ver["valid_to"],
                        "in_force": in_force,
                        "text": ver["text"],
                    }
                )
        else:
            acc.chunks.extend(
                build_chunk_records(
                    provision_iri=provision_iri,
                    redaction_id=None,
                    paragraph=paragraph,
                    rt_url=provision_rt_url(None, rt_url, paragraph),
                    valid_from=kehtiv,
                    valid_to=None,
                    in_force=act_active and compute_in_force(kehtiv, None, eval_date),
                    text=consolidated_text,
                    max_chars=max_chars,
                    **envelope,
                )
            )

        # --- outline entry (skim tier) ---
        acc.outline.append(
            {
                "paragraph": paragraph,
                "label": label,
                "chapter": chapter,
                "summary": truncate_summary(
                    jsonld_text(node.get("estleg:summary")) or label
                ),
                "has_versions": bool(versions),
            }
        )

        # --- context-pack provision entry ---
        references = sorted(set(_ref_ids(node.get("estleg:references"))))
        referenced_by = sorted(set(_ref_ids(node.get("estleg:referencedBy"))))
        interpreted_by = sorted(set(_ref_ids(node.get("estleg:interpretedBy"))))
        acc.case_ids.update(interpreted_by)
        acc.provisions.append(
            {
                "iri": provision_iri,
                "paragraph": paragraph,
                "label": label,
                "chapter": chapter,
                "text": consolidated_text,
                "references": references,
                "referenced_by": referenced_by,
                "interpreted_by": interpreted_by,
                "has_versions": bool(versions),
                "version_count": len(versions),
            }
        )


def build_outline_doc(acc: _LawAccumulator) -> dict:
    """Build the per-law skim outline document."""
    return {
        "law": acc.law_name,
        "abbrev": acc.abbrev,
        "title": acc.title,
        "rt_url": acc.rt_url,
        "provision_count": len(acc.outline),
        "provisions": acc.outline,
    }


def build_context_pack(
    acc: _LawAccumulator,
    *,
    krr_dir: Path,
    decision_index: dict[str, dict],
) -> dict:
    """Build the per-law denormalised bundle (provisions + versions + refs +
    cases + amendments + sanctions) in one fetch."""
    # law_name first (single-file laws), then every peep file stem (multi-part
    # codes whose overlays are keyed by stem, e.g. sanctions_KarS_osa1/_osa2).
    overlay_slugs = (acc.law_name, *acc.file_slugs)
    amendments = _overlay_nodes(
        krr_dir, AMENDMENTS_DIRNAME, "amendments_", *overlay_slugs
    )
    sanctions = _overlay_nodes(
        krr_dir, SANCTIONS_DIRNAME, "sanctions_", *overlay_slugs
    )
    cases = [
        decision_index.get(case_id, {"iri": case_id})
        for case_id in sorted(acc.case_ids)
    ]
    return {
        "law": acc.law_name,
        "abbrev": acc.abbrev,
        "title": acc.title,
        "rt_url": acc.rt_url,
        "kehtiv": acc.kehtiv,
        "in_force": acc.in_force,
        "counts": {
            "provisions": len(acc.provisions),
            "versions": len(acc.versions),
            "amendments": len(amendments),
            "sanctions": len(sanctions),
            "cases": len(cases),
        },
        "provisions": acc.provisions,
        "versions": acc.versions,
        "amendments": amendments,
        "sanctions": sanctions,
        "cases": cases,
    }


# ---------------------------------------------------------------------------
# Corpus enumeration
# ---------------------------------------------------------------------------
def iter_index_laws(krr_dir: Path) -> list[dict]:
    """Return the INDEX ``laws`` entries (sorted by ``name``), or ``[]``."""
    doc = _load_json(krr_dir / "INDEX.json", required=True)
    if not isinstance(doc, dict):
        raise ValueError("Retrieval INDEX must be an object")
    laws = doc.get("laws")
    if not isinstance(laws, list):
        raise ValueError("Retrieval INDEX must contain a laws list")
    return sorted(
        (law for law in laws if isinstance(law, dict) and law.get("name")),
        key=lambda law: law["name"],
    )


def _file_slug(filename: str) -> str:
    """Return the peep stem (the ``_peep.json`` suffix removed)."""
    stem = filename
    stem = stem.removesuffix(".json")
    stem = stem.removesuffix("_peep")
    return stem


# ---------------------------------------------------------------------------
# Served entry point + manifest
# ---------------------------------------------------------------------------
def render_llms_txt(stats: dict) -> str:
    """Render the llms.txt entry point (https://llmstxt.org).

    Links only to artifacts that are actually published: the tagged release
    asset (``chunks.jsonl.gz``) by absolute URL, and files committed next to
    this one (samples, manifest) or in the corpus by relative path. The
    Git-ignored ``chunks.jsonl`` / ``outlines/`` / ``context_packs/`` trees are
    described but never linked (#723).
    """
    keys = ", ".join(CHUNK_KEYS)
    return f"""# Estonian Legal Ontology — Retrieval Projection

> A machine-readable JSON-LD/RDF ontology of Estonian and EU law (~1,120 enacted
> laws plus state and municipal regulations, Riigikohus decisions, and EU acts).
> This retrieval projection flattens the graph into self-contained, citeable
> records so RAG and agent developers do not have to reassemble three nodes
> across two files to cite one paragraph.

The core unit is a provision-version: one §-level provision of an Estonian
state law (INDEX laws only) in one Riigi Teataja redaction, with untruncated
Estonian text. Each JSON Lines record (chunk schema {stats['chunk_schema_version']})
has exactly these keys, in this order:

    {{{keys}}}

Every record is auditable on its own, without this file:
- `chunk_id` — stable id: `<provision_iri>#<redaction_id>`, or
  `<provision_iri>#consolidated` for a provision with no version layer, plus
  `#part_<k>` only when a long § was split (`part_index` of `part_count`).
- `ontology_version` / `evaluation_date` — the build that produced the record
  and the as-of date `in_force` was computed against.
- `act_iri`, `act_title`, `abbrev`, `kehtiv` — the act and the consolidation
  date of the act snapshot the record was read from.
- `rt_url` — the Riigi Teataja page of that redaction with a `#para<N>` anchor
  (`#para<N>b<k>` for § N^k).
- `language` — `{CHUNK_LANGUAGE}` (BCP 47).
IRIs are compact (`estleg:` = {NS}).

Filter `in_force == true` for the law as it stood on `evaluation_date`; group by
`provision_iri` for a paragraph's amendment history.

Build: ontology {stats['ontology_version']}, evaluation date
{stats['evaluation_date']}. Records: {stats['total_chunks']}
({stats['version_records']} version + {stats['consolidated_records']} consolidated);
laws: {stats['laws']}.

## Retrieval artifacts
- [{CHUNKS_ASSET_NAME}]({stats['chunks_asset_url']}): every chunk record, gzipped
  JSON Lines — a release asset of the tagged release v{stats['ontology_version']}
  (built by `build_release_assets.py`; listed with its checksum in the release
  catalogue).
- [chunks.sample.jsonl](chunks.sample.jsonl): the first {SAMPLE_CHUNKS_DEFAULT} records, same schema.
- [manifest.json](manifest.json): counts, chunk schema version, generator commit.
- [sample_outline.json](sample_outline.json): one per-law skim outline —
  `{{paragraph, label, chapter, summary, has_versions}}` per provision.
- [sample_context_pack.json](sample_context_pack.json): one per-law denormalised
  bundle — provisions + versions + references + cases + amendments + sanctions.
- Per-law outlines and context packs for every law are not published; regenerate
  them with `python3 scripts/generate_retrieval_projection.py`.

## Source corpus
- [INDEX.json](../INDEX.json): the law manifest these projections enumerate.
- [combined_ontology.jsonld](../combined_ontology.jsonld): the load-everything
  graph (Git LFS).
- [README](../../README.md): corpus overview, schema, and SPARQL examples.
"""


def _write_text_atomic(path: Path, text: str) -> None:
    """Write ``text`` via a sibling temp file + ``os.replace`` (crash-safe)."""
    tmp = path.with_name(f".{path.name}.tmp")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def write_manifest(out_dir: Path, stats: dict) -> None:
    """Write the deterministic projection manifest."""
    save_json(out_dir / "manifest.json", stats)


def _artifact_size(path: Path) -> int:
    """Return a file's byte size, or 0 if absent."""
    try:
        return path.stat().st_size
    except OSError:
        return 0


def render_readme(stats: dict) -> str:
    """Render the committed README for ``krr_outputs/retrieval/``.

    Generated (not hand-maintained) so it is regenerated on every full run;
    deterministic because it stamps only pinned counts from ``stats``.
    """
    chunks_mb = stats["chunks_bytes"] / 1_000_000
    key_rows = "\n".join(
        f"| `{key}` | {CHUNK_FIELD_DOCS[key][0]} | {CHUNK_FIELD_DOCS[key][1]} |"
        for key in CHUNK_KEYS
    )
    return f"""# Retrieval projection (`krr_outputs/retrieval/`)

A build-time **retrieval projection** of the Estonian Legal Ontology for RAG and
agent developers (tickets #523, #723). It flattens the graph — where one citeable
provision spans the provision node, its `estleg:ProvisionVersion` nodes, and the
act root across two files — into self-contained, citeable records.

Generated by [`scripts/generate_retrieval_projection.py`](../../scripts/generate_retrieval_projection.py)
(this file too). It is **idempotent, network-free, and deterministic** (two runs
over the same corpus are byte-identical): laws are processed in sorted order,
provisions by IRI, versions by `(validFrom, redactionId, IRI)`, and the only
stamps are the pinned `ESTLEG_BUILD_EVALUATION_DATE` and `ONTOLOGY_VERSION`
(plus the generator git commit, recorded in `manifest.json` only).

Current build: ontology {stats['ontology_version']}, evaluation date
{stats['evaluation_date']} — {stats['laws']} laws, {stats['total_chunks']}
chunk records (~{chunks_mb:.0f} MB uncompressed), {stats['outlines']} per-law
outlines and context packs, {stats['cases_indexed']} court decisions indexed.

## Chunk record (schema {stats['chunk_schema_version']})

One JSON object per line, keys always in this order. A record is auditable on
its own: it names the build (`ontology_version`), the as-of date
(`evaluation_date`), the act snapshot (`act_iri`, `kehtiv`), and the exact RT
redaction and § (`rt_url`).

| Key | Type | Meaning / source |
| --- | --- | --- |
{key_rows}

**Splitting.** By default a provision-version is one record. With
`--max-chars N` (minimum {MIN_MAX_CHARS}) a longer text is cut at sentence
boundaries — after `. ! ? ; :` (not after an ordinal or a legal abbreviation
such as `nr.`, `lg.`, `p.`) and before a lõige marker `(N)` — and sentences are
packed greedily into parts of at most N characters (a single longer sentence is
cut at the last space). Parts carry `part_index`/`part_count` and a
`#part_<k>` `chunk_id` suffix. The release asset is built without splitting.

**`rt_url` anchors.** Riigi Teataja renders each § with an element id
`para<N>` (`para<N>b<k>` for § N^k): the ids are in the act XML and the
www.riigiteataja.ee app scrolls to them. The anchor is built from the
`paragraph` label; if it does not parse, `rt_url` is the bare redaction URL.

## Artifacts

| Path | Committed? | What |
| --- | --- | --- |
| `llms.txt` | yes | Served entry point ([llmstxt.org](https://llmstxt.org)). |
| `manifest.json` | yes | Counts, chunk schema version + keys, evaluation date, generator commit, release-asset URL. |
| `README.md` | yes | This file (generated). |
| `chunks.sample.jsonl` | yes | First {SAMPLE_CHUNKS_DEFAULT} chunk records (current schema). |
| `sample_outline.json` | yes | One real per-law outline. |
| `sample_context_pack.json` | yes | One real per-law context pack. |
| `{CHUNKS_ASSET_NAME}` | release asset | Every chunk record, gzipped: <{stats['chunks_asset_url']}>. |
| `chunks.jsonl` | **no** (Git-ignored) | The same records, uncompressed, from a local run. |
| `outlines/<law>.json` | **no** (Git-ignored) | Per-law skim tier: `{{paragraph, label, chapter, summary (<=120), has_versions}}`. |
| `context_packs/<law>.json` | **no** (Git-ignored) | Per-law denormalised bundle: provisions + versions + references + cases + amendments + sanctions in one fetch. |

### Why the heavy files are not committed

`chunks.jsonl`, `outlines/` and `context_packs/` together are several hundred MB
of **derived** data. Rather than commit them, the chunk records ship as the
tagged release asset `{CHUNKS_ASSET_NAME}` (built by
`src/estleg/build_release_assets.py`, the last pipeline step), and a small
committed sample plus the deterministic generator stand in for review. The
whole subtree is excluded from the corpus file counter
(`estleg_common.is_operational_state_file`, same status as
`reports/integration/`) so it never drifts the pinned `metadata.jsonld`
`estleg:totalFiles` count nor reaches `validate_all` / SHACL.

## Regenerate

```bash
python3 scripts/generate_retrieval_projection.py            # full corpus (refreshes the committed files)
python3 scripts/generate_retrieval_projection.py --limit 25 # quick subset
python3 scripts/generate_retrieval_projection.py --max-chars 2000 --out-dir /tmp/estleg-split  # split long §
python3 scripts/generate_retrieval_projection.py --chunks-only --out-dir /tmp/estleg-chunks  # scratch: chunks.jsonl + manifest only (never the committed dir)
python3 scripts/generate_retrieval_projection.py --help     # all options
```

Filter `in_force == true` for the law as it stands at the evaluation date; group
chunk records by `provision_iri` to reconstruct a paragraph's amendment history.
"""


# Derived (generated) artifacts that a ``--chunks-only`` run must NOT leave
# behind — otherwise a prior full run's outlines/context/samples/llms/README
# stay on disk while the manifest reports outlines:0/context_packs:0.
_NON_CHUNK_FILES: tuple[str, ...] = (
    "llms.txt",
    "README.md",
    "chunks.sample.jsonl",
    "sample_outline.json",
    "sample_context_pack.json",
)
_NON_CHUNK_DIRS: tuple[str, ...] = ("outlines", "context_packs")


def _remove_non_chunk_artifacts(out_dir: Path) -> None:
    """Delete every non-chunk artifact so a ``--chunks-only`` directory holds
    exactly ``{chunks.jsonl, manifest.json}`` (consistent with the manifest's
    zeroed outline/context counts)."""
    for name in _NON_CHUNK_FILES:
        (out_dir / name).unlink(missing_ok=True)
    for name in _NON_CHUNK_DIRS:
        shutil.rmtree(out_dir / name, ignore_errors=True)


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------
def generate(
    *,
    krr_dir: Path,
    out_dir: Path,
    eval_date: str,
    limit: int | None = None,
    with_cases: bool = True,
    chunks_only: bool = False,
    sample_chunks: int = SAMPLE_CHUNKS_DEFAULT,
    sample_law: str = SAMPLE_LAW_DEFAULT,
    max_chars: int | None = None,
) -> dict:
    """Generate the retrieval projection; return a stats/manifest dict.

    ``max_chars`` (default ``None`` = never split) splits a provision-version
    whose text is longer than that many characters into sentence-bounded
    parts (see :func:`split_text`).
    """
    try:
        eval_date = date.fromisoformat(eval_date).isoformat()
    except (ValueError, TypeError) as exc:
        raise ValueError("--evaluation-date must be an ISO calendar date") from exc
    if max_chars is not None and max_chars < MIN_MAX_CHARS:
        raise ValueError(
            f"--max-chars must be at least {MIN_MAX_CHARS} (got {max_chars})"
        )
    # --chunks-only cleans the directory down to {chunks.jsonl, manifest.json}.
    # Refuse to do that to the COMMITTED projection: it would delete the tracked,
    # reviewable README.md / llms.txt / sample_*.json and re-zero their manifest
    # counts. chunks-only is a scratch/CI mode — require an explicit --out-dir.
    if chunks_only and out_dir.resolve() == (KRR_DIR / DEFAULT_OUT_DIRNAME).resolve():
        raise ValueError(
            "--chunks-only would clean the committed projection at "
            f"{KRR_DIR / DEFAULT_OUT_DIRNAME} (deleting the tracked "
            "README.md / llms.txt / samples and re-zeroing their manifest "
            "counts). Pass --out-dir <scratch-dir> for a chunks-only "
            "projection; rebuild the committed projection with a full run."
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    outlines_dir = out_dir / "outlines"
    context_dir = out_dir / "context_packs"
    # Build the per-law trees in sibling .tmp dirs and atomically swap them in
    # at the end (mirrors the chunks.jsonl temp + os.replace below). This makes
    # a crash mid-run leave the previous tree intact, AND guarantees the final
    # tree contains exactly this run's laws -- without it, a `--limit N` run
    # would leave an earlier full run's per-law files on disk while the manifest
    # reported only N (stale-output drift).
    outlines_tmp = out_dir / "outlines.tmp"
    context_tmp = out_dir / "context_packs.tmp"
    if not chunks_only:
        for tmp in (outlines_tmp, context_tmp):
            if tmp.exists():
                shutil.rmtree(tmp)
            tmp.mkdir(parents=True, exist_ok=True)

    registry = _load_json(ABBREV_REGISTRY_PATH)
    if not isinstance(registry, dict):
        registry = {}
    decision_index = (
        build_decision_index(krr_dir) if (with_cases and not chunks_only) else {}
    )

    laws = iter_index_laws(krr_dir)
    if limit is not None:
        laws = laws[:limit]

    versions_dir = krr_dir / PROVISION_VERSIONS_DIRNAME
    version_map = load_version_map(versions_dir)
    chunks_tmp = out_dir / "chunks.jsonl.tmp"
    stats = {
        "ontology_version": ONTOLOGY_VERSION,
        "evaluation_date": eval_date,
        "chunk_schema_version": CHUNK_SCHEMA_VERSION,
        "chunk_keys": list(CHUNK_KEYS),
        "language": CHUNK_LANGUAGE,
        "max_chars": max_chars,
        "generator": "src/estleg/generate_retrieval_projection.py",
        "generator_commit": generator_commit(),
        "chunks_asset": CHUNKS_ASSET_NAME,
        "chunks_asset_url": chunks_asset_url(),
        "laws": 0,
        "laws_skipped_deprecated": 0,
        "laws_skipped_non_peep": 0,
        "total_chunks": 0,
        "version_records": 0,
        "consolidated_records": 0,
        "split_provision_versions": 0,
        "outlines": 0,
        "context_packs": 0,
        "cases_indexed": len(decision_index),
    }
    sample_chunk_lines: list[str] = []
    sample_outline: dict | None = None
    sample_context: dict | None = None
    first_acc: _LawAccumulator | None = None
    seen_chunk_ids: set[str] = set()

    with open(chunks_tmp, "w", encoding="utf-8") as chunks_fh:
        for law in laws:
            law_name = law["name"]
            files = sorted(law.get("files") or [])
            # Skip non-enacted INDEX entries that carry no peep file — the
            # *_owl.jsonld TBox modules (karistusseadustik_eriosa_owl,
            # tsus_osa7_138_169_owl), which would otherwise emit an empty
            # outline + context pack and inflate the law count.
            if not any(f.endswith("_peep.json") for f in files):
                stats["laws_skipped_non_peep"] += 1
                continue
            acc = _LawAccumulator(law_name)
            deprecated = False
            for filename in files:
                doc = _load_graph_json(krr_dir / filename)
                is_dep, _ = act_deprecation(doc)
                if is_dep:
                    deprecated = True
                    break
                file_slug = _file_slug(filename)
                process_law_file(
                    doc,
                    file_slug=file_slug,
                    law_name=law_name,
                    registry=registry,
                    version_map=version_map,
                    eval_date=eval_date,
                    acc=acc,
                    max_chars=max_chars,
                )
            if deprecated:
                stats["laws_skipped_deprecated"] += 1
                continue

            stats["laws"] += 1
            for record in acc.chunks:
                if record["chunk_id"] in seen_chunk_ids:
                    raise ValueError(f"duplicate chunk id: {record['chunk_id']}")
                seen_chunk_ids.add(record["chunk_id"])
                line = json.dumps(record, ensure_ascii=False)
                chunks_fh.write(line + "\n")
                # version/consolidated count provision-version UNITS (a split
                # unit is counted once, at its first part).
                if record["part_index"] == 1:
                    if record["redaction_id"] is None:
                        stats["consolidated_records"] += 1
                    else:
                        stats["version_records"] += 1
                    if record["part_count"] > 1:
                        stats["split_provision_versions"] += 1
                if len(sample_chunk_lines) < sample_chunks:
                    sample_chunk_lines.append(line)
            stats["total_chunks"] += len(acc.chunks)

            if not chunks_only:
                outline_doc = build_outline_doc(acc)
                context_doc = build_context_pack(
                    acc, krr_dir=krr_dir, decision_index=decision_index
                )
                save_json(outlines_tmp / f"{law_name}.json", outline_doc)
                save_json(context_tmp / f"{law_name}.json", context_doc)
                stats["outlines"] += 1
                stats["context_packs"] += 1
                if law_name == sample_law:
                    sample_outline = outline_doc
                    sample_context = context_doc
            if first_acc is None:
                first_acc = acc

    os.replace(chunks_tmp, out_dir / "chunks.jsonl")

    if not chunks_only:
        # Atomically replace the per-law trees with this run's freshly built
        # ones, dropping any stale files left by a previous (e.g. unlimited) run
        # so the on-disk tree always matches the manifest counts.
        for tmp, final in (
            (outlines_tmp, outlines_dir),
            (context_tmp, context_dir),
        ):
            if final.exists():
                shutil.rmtree(final)
            os.replace(tmp, final)

    # Fall back to the first processed law for samples when the configured
    # sample law is absent (e.g. a --limit run or a test corpus).
    if not chunks_only and sample_outline is None and first_acc is not None:
        sample_outline = build_outline_doc(first_acc)
        sample_context = build_context_pack(
            first_acc, krr_dir=krr_dir, decision_index=decision_index
        )

    stats["chunks_bytes"] = _artifact_size(out_dir / "chunks.jsonl")

    if not chunks_only:
        # Served entry point + README + samples (committed; heavy trees ignored).
        _write_text_atomic(out_dir / "llms.txt", render_llms_txt(stats))
        _write_text_atomic(out_dir / "README.md", render_readme(stats))
        _write_text_atomic(
            out_dir / "chunks.sample.jsonl",
            "".join(line + "\n" for line in sample_chunk_lines),
        )
        if sample_outline is not None:
            save_json(out_dir / "sample_outline.json", sample_outline)
        if sample_context is not None:
            save_json(out_dir / "sample_context_pack.json", sample_context)
    else:
        # --chunks-only: drop any non-chunk artifacts a prior full run left so
        # the directory is exactly {chunks.jsonl, manifest.json}, matching the
        # manifest's zeroed outline/context counts.
        _remove_non_chunk_artifacts(out_dir)

    write_manifest(out_dir, stats)
    return stats


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Emit the retrieval projection (chunks / outlines / "
        "context packs / llms.txt) for RAG and agent developers (#523)."
    )
    parser.add_argument("--krr-dir", type=Path, default=KRR_DIR)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="output directory (default: <krr-dir>/retrieval)",
    )
    parser.add_argument(
        "--evaluation-date",
        default=BUILD_EVALUATION_DATE,
        help="pinned as-of date for in_force selection (YYYY-MM-DD)",
    )
    parser.add_argument(
        "--limit", type=int, default=None, help="process only the first N laws"
    )
    parser.add_argument(
        "--no-cases",
        action="store_true",
        help="skip the court-decision index (faster; context-pack cases become "
        "bare IRIs)",
    )
    parser.add_argument(
        "--chunks-only",
        action="store_true",
        help="emit only chunks.jsonl + manifest (skip outlines/context packs/"
        "samples)",
    )
    parser.add_argument(
        "--sample-chunks", type=int, default=SAMPLE_CHUNKS_DEFAULT
    )
    parser.add_argument("--sample-law", default=SAMPLE_LAW_DEFAULT)
    parser.add_argument(
        "--max-chars",
        type=int,
        default=None,
        help="split a provision-version whose text exceeds N characters into "
        "sentence-bounded parts (part_index/part_count, chunk_id #part_<k>); "
        f"default: never split; minimum {MIN_MAX_CHARS}",
    )
    args = parser.parse_args(argv)

    out_dir = args.out_dir or (args.krr_dir / DEFAULT_OUT_DIRNAME)
    try:
        stats = generate(
            krr_dir=args.krr_dir,
            out_dir=out_dir,
            eval_date=args.evaluation_date,
            limit=args.limit,
            with_cases=not args.no_cases,
            chunks_only=args.chunks_only,
            sample_chunks=args.sample_chunks,
            sample_law=args.sample_law,
            max_chars=args.max_chars,
        )
    except ValueError as exc:
        parser.error(str(exc))
    print(
        "retrieval projection: "
        f"{stats['laws']} laws, {stats['total_chunks']} chunks "
        f"({stats['version_records']} version + "
        f"{stats['consolidated_records']} consolidated, "
        f"{stats['split_provision_versions']} split), "
        f"{stats['outlines']} outlines, {stats['context_packs']} context packs, "
        f"{stats['cases_indexed']} cases indexed, "
        f"{stats['laws_skipped_deprecated']} deprecated laws skipped"
    )
    print(f"  chunks.jsonl: {stats['chunks_bytes']:,} bytes -> {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
